# Generated by Django 3.0.7 on 2021-04-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('payment_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHasProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40)),
                ('imei_no', models.IntegerField()),
                ('price', models.IntegerField()),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.Purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.Supplier'),
        ),
    ]
