# Generated by Django 3.0.7 on 2021-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
