# Generated by Django 3.0.7 on 2021-04-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210402_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('customer', models.CharField(max_length=40)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchasehasproduct',
            name='pur_prod',
            field=models.BooleanField(default=False),
        ),
    ]
