# Generated by Django 3.0.7 on 2021-04-06 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210405_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesHasProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_no', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.PurchaseHasProduct')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.Sales')),
            ],
        ),
    ]
