# Generated by Django 3.0.7 on 2021-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210414_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('remark', models.CharField(max_length=50)),
                ('check', models.BooleanField(default=False)),
            ],
        ),
    ]
