# Generated by Django 3.0.7 on 2021-04-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='saleshasproduct',
            name='imei_no',
            field=models.IntegerField(null=True),
        ),
    ]
