# Generated by Django 3.0.7 on 2021-04-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210421_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehasproduct',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Purchase'),
        ),
    ]
