# Generated by Django 3.0.7 on 2021-05-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210424_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehasproduct',
            name='imei_no',
            field=models.BigIntegerField(),
        ),
    ]
