# Generated by Django 3.0.7 on 2021-05-24 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20210504_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHasImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='my_img')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.PurchaseHasProduct')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Purchase')),
            ],
        ),
    ]
