# Generated by Django 3.0.7 on 2021-05-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_producthasimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthasimg',
            name='purchase',
        ),
        migrations.AlterField(
            model_name='producthasimg',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.PurchaseHasProduct'),
        ),
    ]
