# Generated by Django 3.0.7 on 2021-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20210524_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_acc',
            field=models.BooleanField(default=False),
        ),
    ]
