# Generated by Django 3.0.7 on 2021-06-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_account_is_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
